### ISSUE TITLE
The field name should be split into first and second name

### ISSUE THREAD

**Issue by gerchicov-bp** [RurioLuca/QrCardParsing#1]
https://www.nttdocomo.co.jp/english/service/developer/make/content/barcode/function/application/addressbook/index.html
due to this documentation there are some special obstacles when you have only first/second name and both of them.

Check the other cases too.

**Comment by RurioLuca** [comment]
I'm sorry but I do not understand very well, the MeCard format contains "Name", which you can enter first and last name split by  ','
Did you mean that?

**Comment by gerchicov-bp** [comment]
```Name``` - ```When a field is divided by a comma (,), the first half is treated as the last name and the second half is treated as the first name.```
But in your code you use one field - "name"

**Comment by RurioLuca** [comment]
Well, So in Bean would MeCard two variables , name and surname?

**Comment by gerchicov-bp** [comment]
yes, and surname may be empty

**Comment by RurioLuca** [comment]
Please update your version ;-)

dependencies {
compile 'it.auron:mecard-parser:1.0.6'
}
