### ISSUE TITLE
How to parse multiple emails in vCard?

### ISSUE THREAD

**Issue by taar1** [RurioLuca/QrCardParsing#2]
I tried out your example but it only reads one email address. There's vCards that have multiple email addresses (and phone numbers etc.) saved. i.e.
TEL;:+81-80-4116-1790
TEL;:+41786128748
EMAIL;PREF;HOME:xxxxxx@gmail.com
EMAIL:test@softbank.ne.jp
EMAIL;WORK:profes@hotmail.com
EMAIL;X-Sonstiges:othermailyahoo.com

I only see one method to get one email address:
VCard vCard = VCardParser.parse(vCardString);
vCard.getEmail();

How to get the other email addresses and other fields?

**Comment by RurioLuca** [comment]
Thanks for the report, now I will check the problem!

**Comment by RurioLuca** [comment]
Hi ;-)


Thanks for your report, I have now updated the library.

Please update your version!

dependencies {
compile 'it.auron:mecard-parser:1.0.9'
}



https://github.com/RurioLuca/QrCardParsing

Let me know how you look ;-)

Best regards

Rurio Luca

2017-04-23 18:29 GMT+02:00 Dominik <notifications@github.com>:

**Comment by RurioLuca** [comment]
The bug should be fixed, I've released version 1.0.9 now

**Comment by taar1** [comment]
Thanks for the quick reaction. I will try it out tonight.
