### ISSUE TITLE
in vCard class you doing worng forget to chnage key  

### ISSUE THREAD

**Issue by zadShaikh** [RurioLuca/QrCardParsing#5]
if (telephones.size() != 0) {
            for (String s : telephones) {
                if (!TextUtils.isEmpty(s)) {
                    meCardString.append(VCardCostant.KEY_LINE_ESCAPE).append(VCardCostant.KEY_EMAIL).append(":").append(s);
                }
            }
        }

this is a telephone field but you store in email

**Comment by RurioLuca** [comment]
Tanks you for the segnalation.

I will solve the problem as soon as possible

**Comment by RurioLuca** [comment]
I have just fix it.
Thank you again for the segnalation.

update your version:
implementation 'it.auron:mecard-parser:1.1.3'
