### ISSUE TITLE
how to set qrcode size in vcard

### ISSUE THREAD

**Issue by zadShaikh** [RurioLuca/QrCardParsing#6]

**Comment by RurioLuca** [comment]
This library only performs the generation and parsing of a content of the QrCode, it does not generate the image.

In the sample app I used QrGen,
the dimensions are set up like this:

`QRCode.from(vCard.buildString()).withSize(250, 250).bitmap();`

in any case, I refer you to the link to the specific library.
https://github.com/kenglxn/QRGen

**Comment by zadShaikh** [comment]
Thank you so much sir
